# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fucking Code Signing
email: your-email@domain.com
description: >
  A website of helpful tips for resolving fucking code signing issues in Xcode.
baseurl: ""
url: "http://fuckingcodesigning.com" # the base hostname & protocol for your site
twitter_username: dtrenz
github_username:  dtrenz

# Build settings
markdown: kramdown
exclude: [vendor]
